# ==============================================================
# = ASSOCIATIONS WEB SERVICE
# ==============================================================
# ==============================================================
# = NOTE
# ==============================================================   
# build:
# mvn -D maven.test.skip=true clean install

# run java JAR with specific profile ID:
# java -jar -Dspring.profiles.active=zone[n] -DMySqlIp=127.0.0.1 -DZuulIp=127.0.0.1 -Xmx96m -Xss512k NameApp.jar
# ==============================================================
# = PROFILE: zone1
# ==============================================================
spring:
  profiles: zone1
  application:
    name: ASSOCIATIONS-WEB-SERVICE
  cloud:
    discovery:
      enabled: false
  sleuth:
    sampler:
      probability: 1.0
    traceId128: false
  # ==============================================================
  # = DBMS MySQL Parameters
  # ==============================================================
  datasource:
    initialization-mode: always
    username: microService
    password: 20240307Tp!
    url: jdbc:mysql://${MySqlIp}:3306/tarahumara?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    hikari:
      connection-timeout: 40000
      max-lifetime: 40000
      validation-timeout: 10000
      maximum-pool-size: 10 
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    # spring.jackson.time-zone=UTC

server:
  port: 5093

# ==============================================================
# = Proprietà Livello Log
# = Default ERROR, WARN e INFO 
# = Levels: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
# ==============================================================   
logging:
  file:
    name: 'logs/associations-web-service-zone1.log'
    max-size: 10MB
  # Livello del Log generale
  level:
    root: INFO 
    # Livello di log specifico
    # org.springframework.security: DEBUG
    org.hibernate: INFO

# ==============================================================
# = ACTUATOR
# ==============================================================
management:
  endpoints:
    web:
      exposure: 
        include: health, info, shutdown, metrics, mappings
    # ACTUATOR - SHUTDOWN
    shutdown:
      enabled: true
  endpoint:
     health:
      show-details: always

# ACTUATOR - INFO
info:
  app: @project.version@
  env: prod
  profile: zone1
  author:
    name: Paolo
    surname: Acquaviva
    contact: paoloacqua@hotmail.it

# ==============================================================
# = EUREKA  
# ==============================================================
# eureka:
#   instance:
#     #intervallo di attesa prima della rimozione del servizio (def 90 sec)
#     lease-expiration-duration-in-seconds: 60 
#     #intervallo di invio dell'heartbeat (def 30 sec)
#     leaseRenewalIntervalInSeconds: 10
#     #id di identificazione dell'istanza
#     instanceId: ${spring.application.name}-1
#     #registrazione per indirizzo ip (defualt hostname)
#     preferIpAddress: true
#   client:
#     registerWithEureka: true
#     fetch-registry: true
#     serviceUrl:
#       defaultZone: http://${eurekasrv}:8761/eureka/

# ==============================================================
# = RIBBON  
# ==============================================================
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
ZUUL-API-GATEWAY:
  ribbon:
    listOfServers: http://${ZuulIp}:8120